import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/layouts/navbar/navbar';
import Footer from '@/layouts/footer/footer';
import ContentWrapper from '@/layouts/contentWrapper/contentWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'UKS Git',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContentWrapper>
          <Navbar />
          {children}
          <Footer />
        </ContentWrapper>
      </body>
    </html>
  );
}
