import ContentWrapper from '@/layouts/contentWrapper/contentWrapper';
import Footer from '@/layouts/footer/footer';
import Navbar from '@/layouts/navbar/navbar';
import StoreProvider from '@/store/storeProvider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'UKS Git',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ContentWrapper>
            <Navbar />
            {children}
            <Footer />
          </ContentWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
