name: Pull Request Open

on:
  pull_request:
    paths:
      - "Backend/**"
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore Backend/Backend.csproj

      - name: Build
        run: dotnet build --configuration Release Backend/Backend.csproj

      - name: Test
        run: dotnet test --configuration Release --no-restore Backend/Backend.csproj

      - name: Build Docker image
        run: docker build -f Backend/Dockerfile Backend
